2022-03-18 15:51:54,474 INFO    MainThread:84812 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/.config/wandb/settings
2022-03-18 15:51:54,474 INFO    MainThread:84812 [wandb_setup.py:_flush():75] Loading settings from /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/settings
2022-03-18 15:51:54,474 INFO    MainThread:84812 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-18 15:51:54,474 INFO    MainThread:84812 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-18 15:51:54,474 INFO    MainThread:84812 [wandb_init.py:_log_setup():405] Logging user logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220318_155154-6p2ah1yx/logs/debug.log
2022-03-18 15:51:54,474 INFO    MainThread:84812 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/AFischer/PycharmProjects/cocoon-project/docs/wandb/run-20220318_155154-6p2ah1yx/logs/debug-internal.log
2022-03-18 15:51:54,474 INFO    MainThread:84812 [wandb_init.py:init():439] calling init triggers
2022-03-18 15:51:54,474 INFO    MainThread:84812 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-18 15:51:54,474 INFO    MainThread:84812 [wandb_init.py:init():458] re-initializing run, found existing run on stack: fgufctaa
2022-03-18 15:51:54,475 INFO    MainThread:84812 [wandb_run.py:finish():1539] finishing run afischer/tcn_samp_en-project/fgufctaa
2022-03-18 15:51:54,475 INFO    MainThread:84812 [jupyter.py:save_history():429] not saving jupyter history
2022-03-18 15:51:54,476 INFO    MainThread:84812 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-18 15:51:54,476 INFO    MainThread:84812 [wandb_init.py:_jupyter_teardown():337] cleaning up jupyter logic
2022-03-18 15:51:54,476 INFO    MainThread:84812 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-18 15:51:54,480 INFO    MainThread:84812 [wandb_run.py:_restore():1674] restore
2022-03-18 15:51:55,416 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-18 15:51:55,738 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 825
}

2022-03-18 15:51:56,475 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 3437
}

2022-03-18 15:51:56,584 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 9597
}

2022-03-18 15:51:56,694 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 9597
}

2022-03-18 15:51:56,797 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 825
  total_bytes: 9597
}

2022-03-18 15:51:56,906 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9597
  total_bytes: 9597
}

2022-03-18 15:51:57,013 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9597
  total_bytes: 9597
}

2022-03-18 15:51:57,136 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9597
  total_bytes: 9597
}

2022-03-18 15:51:57,246 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9597
  total_bytes: 9597
}

2022-03-18 15:51:57,353 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9597
  total_bytes: 9597
}

2022-03-18 15:51:57,971 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9597
  total_bytes: 9597
}

2022-03-18 15:51:58,486 INFO    MainThread:84812 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9597
  total_bytes: 9597
}
local_info {
}

2022-03-18 15:51:59,627 INFO    MainThread:84812 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-18 15:51:59,627 INFO    MainThread:84812 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-18 15:51:59,628 INFO    MainThread:84812 [wandb_run.py:_footer_sync_info():2822] logging synced files
2022-03-18 15:51:59,631 INFO    MainThread:84812 [wandb_init.py:init():492] starting backend
2022-03-18 15:51:59,631 INFO    MainThread:84812 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-03-18 15:51:59,633 INFO    MainThread:84812 [backend.py:ensure_launched():219] starting backend process...
2022-03-18 15:51:59,646 INFO    MainThread:84812 [backend.py:ensure_launched():224] started backend process with pid: 85273
2022-03-18 15:51:59,647 INFO    MainThread:84812 [wandb_init.py:init():501] backend started and connected
2022-03-18 15:51:59,667 INFO    MainThread:84812 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-18 15:51:59,667 INFO    MainThread:84812 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-18 15:51:59,667 INFO    MainThread:84812 [wandb_init.py:init():565] updated telemetry
2022-03-18 15:51:59,697 INFO    MainThread:84812 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-18 15:52:00,609 INFO    MainThread:84812 [wandb_run.py:_on_init():1759] communicating current version
2022-03-18 15:52:00,661 INFO    MainThread:84812 [wandb_run.py:_on_init():1763] got version response 
2022-03-18 15:52:00,662 INFO    MainThread:84812 [wandb_init.py:init():625] starting run threads in backend
2022-03-18 15:52:02,678 INFO    MainThread:84812 [wandb_run.py:_console_start():1733] atexit reg
2022-03-18 15:52:02,679 INFO    MainThread:84812 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.WRAP
2022-03-18 15:52:02,679 INFO    MainThread:84812 [wandb_run.py:_redirect():1643] Wrapping output streams.
2022-03-18 15:52:02,679 INFO    MainThread:84812 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-18 15:52:02,679 INFO    MainThread:84812 [wandb_init.py:init():664] run started, returning control to user process
2022-03-18 15:59:32,661 INFO    MainThread:84812 [wandb_config.py:__setitem__():153] config set batch_size = 10 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fa08a4f2a90>>
2022-03-18 15:59:32,663 INFO    MainThread:84812 [wandb_run.py:_config_callback():992] config_cb batch_size 10 None
2022-03-18 15:59:32,665 INFO    MainThread:84812 [wandb_config.py:__setitem__():153] config set epochs = 40 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fa08a4f2a90>>
2022-03-18 15:59:32,665 INFO    MainThread:84812 [wandb_run.py:_config_callback():992] config_cb epochs 40 None
2022-03-18 15:59:32,665 INFO    MainThread:84812 [wandb_config.py:__setitem__():153] config set lr = 0.001100908904544886 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fa08a4f2a90>>
2022-03-18 15:59:32,665 INFO    MainThread:84812 [wandb_run.py:_config_callback():992] config_cb lr 0.001100908904544886 None
2022-03-18 15:59:32,666 INFO    MainThread:84812 [wandb_config.py:__setitem__():153] config set no_cuda = False - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fa08a4f2a90>>
2022-03-18 15:59:32,666 INFO    MainThread:84812 [wandb_run.py:_config_callback():992] config_cb no_cuda False None
2022-03-18 15:59:32,666 INFO    MainThread:84812 [wandb_config.py:__setitem__():153] config set seed = 42 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fa08a4f2a90>>
2022-03-18 15:59:32,667 INFO    MainThread:84812 [wandb_run.py:_config_callback():992] config_cb seed 42 None
2022-03-18 15:59:34,036 INFO    MainThread:84812 [wandb_watch.py:watch():47] Watching
2022-03-18 16:00:38,906 INFO    MainThread:84812 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 0
2022-03-18 16:00:38,909 INFO    MainThread:84812 [wandb_run.py:_restore():1674] restore
